# Site settings
title: Mochawesome
email: your-email@domain.com
url: https://adamgruber.github.io/mochawesome
baseurl: /mochawesome
description: "Mochawesome is a custom reporter for the testing framework, mocha. It generates a full fledged HTML/CSS report that helps visualize your test suites."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#ef8b09'

# Footer settings
footer: Adam Gruber

# Build settings
markdown: kramdown
permalink: pretty

exclude: 
  - node_modules